### ISSUE TITLE
为什么transformers的RoPE实现会想到每隔d/2为一组呢

### ISSUE THREAD

**Issue by SchweitzerGAO** [YueZhengMeng/MyLlama#1]
不会是为了回避复数运算吧

**Comment by YueZhengMeng** [comment]
我看到的一种比较合理的解释是：这样的实现计算步骤更少，改写为CUDA实现也更简单

**Comment by SchweitzerGAO** [comment]
乐佬给个链接，我看看

**Comment by YueZhengMeng** [comment]
https://github.com/huggingface/transformers/issues/30872
https://blog.eleuther.ai/rotary-embeddings/

**Comment by YueZhengMeng** [comment]
https://github.com/huggingface/transformers/issues/30872
